# Generated by Django 5.1.6 on 2025-02-11 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rutinas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='creada_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ejercicioenrutina',
            name='rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='rutinas.rutina'),
        ),
        migrations.AlterUniqueTogether(
            name='ejercicioenrutina',
            unique_together={('rutina', 'orden')},
        ),
    ]
