# Generated by Django 5.1.6 on 2025-02-11 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='grupo_muscular',
            field=models.CharField(choices=[('piernas', 'Piernas'), ('pecho', 'Pecho'), ('espalda', 'Espalda'), ('hombros', 'Hombros'), ('brazos', 'Brazos'), ('abdominales', 'Abdominales'), ('fullbody', 'Full Body')], default='fullbody', max_length=50, verbose_name='Grupo muscular'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='nivel_dificultad',
            field=models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='principiante', max_length=20, verbose_name='Nivel de dificultad'),
        ),
        migrations.CreateModel(
            name='ProgramacionRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], default='LUN', max_length=3, verbose_name='Día de la semana')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora de la rutina')),
                ('activa', models.BooleanField(default=True, verbose_name='Programación activa')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='rutinas.rutina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dia_semana', 'hora'],
                'unique_together': {('usuario', 'dia_semana')},
            },
        ),
    ]
