# Generated by Django 5.1.6 on 2025-02-11 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rutinas', '0003_alter_ejercicio_grupo_muscular_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora del entrenamiento')),
                ('completado', models.BooleanField(default=True, verbose_name='Entrenamiento completado')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='rutinas.rutina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_entrenamientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de entrenamiento',
                'verbose_name_plural': 'Registros de entrenamientos',
                'ordering': ['-fecha'],
            },
        ),
    ]
